// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodingPlanService 提供 Coding Plan 账号配置管理与用量查询。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteCodingPlan 删除账号配置。
 */
export function DeleteCodingPlan(id: string): $CancellablePromise<void> {
    return $Call.ByID(1797084418, id);
}

/**
 * ListCodingPlans 返回已配置的账号列表。
 */
export function ListCodingPlans(): $CancellablePromise<$models.CodingPlanAccount[]> {
    return $Call.ByID(2718488746).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * QueryCodingPlanUsage 查询单个账号的实时用量。账号不存在返回 Go 错误；
 * 查询失败（网络/鉴权/业务/解析）不返回错误，而是带 Status/Error 的结果。
 */
export function QueryCodingPlanUsage(id: string): $CancellablePromise<$models.CodingPlanUsage> {
    return $Call.ByID(773619020, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveCodingPlan 新增或更新账号；ID 为空时生成新 ID，返回落库后的账号。
 */
export function SaveCodingPlan(account: $models.CodingPlanAccount): $CancellablePromise<$models.CodingPlanAccount> {
    return $Call.ByID(1320676376, account).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CodingPlanAccount.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CodingPlanUsage.createFrom;
