// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PortService from "./portservice.js";
import * as ServicesService from "./servicesservice.js";
import * as StartupService from "./startupservice.js";
import * as UpdateService from "./updateservice.js";
export {
    PortService,
    ServicesService,
    StartupService,
    UpdateService
};

export {
    KillProcessResult,
    PortEntry,
    PortListResult,
    ServiceEntry,
    StartupEntry,
    UpdateInfo
} from "./models.js";
