// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CodingPlanAccount 描述一条 Coding Plan 用量监控账号的配置。
 */
export class CodingPlanAccount {
    "id": string;

    /**
     * 显示名，留空时由前端回退为供应商名
     */
    "name": string;

    /**
     * zhipu / kimi / minimax / zenmux / deepseek
     */
    "provider": string;

    /**
     * zenmux 必填（完整查询端点）；zhipu/minimax 用于区分国内/国际站
     */
    "baseUrl": string;
    "apiKey": string;

    /**
     * 余额预警阈值（元），0 = 不提醒；仅余额型供应商（deepseek）使用
     */
    "alertAmount": number;
    "createdAt": number;

    /** Creates a new CodingPlanAccount instance. */
    constructor($$source: Partial<CodingPlanAccount> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("alertAmount" in $$source)) {
            this["alertAmount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodingPlanAccount instance from a string or object.
     */
    static createFrom($$source: any = {}): CodingPlanAccount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodingPlanAccount($$parsedSource as Partial<CodingPlanAccount>);
    }
}

/**
 * CodingPlanBalance 描述余额型供应商（DeepSeek）的账户余额，金额单位为账户币种。
 */
export class CodingPlanBalance {
    /**
     * "CNY" / "USD"
     */
    "currency": string;

    /**
     * 总余额（赠金 + 充值）
     */
    "total": number;

    /**
     * 未过期赠金
     */
    "granted": number;

    /**
     * 充值余额
     */
    "toppedUp": number;

    /**
     * 余额是否足以进行 API 调用
     */
    "available": boolean;

    /** Creates a new CodingPlanBalance instance. */
    constructor($$source: Partial<CodingPlanBalance> = {}) {
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("granted" in $$source)) {
            this["granted"] = 0;
        }
        if (!("toppedUp" in $$source)) {
            this["toppedUp"] = 0;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodingPlanBalance instance from a string or object.
     */
    static createFrom($$source: any = {}): CodingPlanBalance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodingPlanBalance($$parsedSource as Partial<CodingPlanBalance>);
    }
}

/**
 * CodingPlanQuota 描述一个用量窗口（5 小时 / 周）的百分比与重置时间。
 */
export class CodingPlanQuota {
    /**
     * 已用百分比（0-100 基准；超界不裁剪，展示策略交给前端）
     */
    "usedPercent": number;

    /**
     * 重置时间 ISO 8601，空表示未知
     */
    "resetsAt": string;

    /**
     * 补充用量文本（如 ZenMux 的 "$3.20 / $7.50"），无则空
     */
    "usedLabel": string;

    /** Creates a new CodingPlanQuota instance. */
    constructor($$source: Partial<CodingPlanQuota> = {}) {
        if (!("usedPercent" in $$source)) {
            this["usedPercent"] = 0;
        }
        if (!("resetsAt" in $$source)) {
            this["resetsAt"] = "";
        }
        if (!("usedLabel" in $$source)) {
            this["usedLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodingPlanQuota instance from a string or object.
     */
    static createFrom($$source: any = {}): CodingPlanQuota {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodingPlanQuota($$parsedSource as Partial<CodingPlanQuota>);
    }
}

/**
 * CodingPlanUsage 是单账号一次用量查询的结果；失败不返回 Go 错误，
 * 而是 Status=expired/error + Error 带原因，便于前端按卡片展示失败态。
 * 配额型供应商填 FiveHour/Weekly，余额型供应商填 Balance（互斥，nil 区分形态）。
 */
export class CodingPlanUsage {
    "accountId": string;

    /**
     * 套餐等级（Lite/Pro/Max 等），无则空
     */
    "planName": string;

    /**
     * ok / expired / error
     */
    "status": string;

    /**
     * 5 小时窗口；nil 表示无该桶
     */
    "fiveHour": CodingPlanQuota | null;

    /**
     * 周（7 天）窗口；nil 表示套餐无周限额
     */
    "weekly": CodingPlanQuota | null;

    /**
     * 余额（DeepSeek）；nil 表示配额型
     */
    "balance": CodingPlanBalance | null;
    "error": string;
    "queriedAt": number;

    /** Creates a new CodingPlanUsage instance. */
    constructor($$source: Partial<CodingPlanUsage> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("planName" in $$source)) {
            this["planName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("fiveHour" in $$source)) {
            this["fiveHour"] = null;
        }
        if (!("weekly" in $$source)) {
            this["weekly"] = null;
        }
        if (!("balance" in $$source)) {
            this["balance"] = null;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("queriedAt" in $$source)) {
            this["queriedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodingPlanUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): CodingPlanUsage {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fiveHour" in $$parsedSource) {
            $$parsedSource["fiveHour"] = $$createField3_0($$parsedSource["fiveHour"]);
        }
        if ("weekly" in $$parsedSource) {
            $$parsedSource["weekly"] = $$createField4_0($$parsedSource["weekly"]);
        }
        if ("balance" in $$parsedSource) {
            $$parsedSource["balance"] = $$createField5_0($$parsedSource["balance"]);
        }
        return new CodingPlanUsage($$parsedSource as Partial<CodingPlanUsage>);
    }
}

export class KillProcessResult {
    "pid": number;
    "message": string;

    /** Creates a new KillProcessResult instance. */
    constructor($$source: Partial<KillProcessResult> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillProcessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KillProcessResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillProcessResult($$parsedSource as Partial<KillProcessResult>);
    }
}

export class PortEntry {
    "protocol": string;
    "localAddr": string;
    "localPort": number;
    "remoteAddr": string;
    "remotePort": number;
    "state": string;
    "pid": number;
    "process": string;
    "path": string;

    /** Creates a new PortEntry instance. */
    constructor($$source: Partial<PortEntry> = {}) {
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("process" in $$source)) {
            this["process"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PortEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortEntry($$parsedSource as Partial<PortEntry>);
    }
}

export class PortListResult {
    "ports": PortEntry[];
    "tcpCount": number;
    "udpCount": number;
    "listeningCount": number;
    "processCount": number;
    "warnings": string[];

    /** Creates a new PortListResult instance. */
    constructor($$source: Partial<PortListResult> = {}) {
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("tcpCount" in $$source)) {
            this["tcpCount"] = 0;
        }
        if (!("udpCount" in $$source)) {
            this["udpCount"] = 0;
        }
        if (!("listeningCount" in $$source)) {
            this["listeningCount"] = 0;
        }
        if (!("processCount" in $$source)) {
            this["processCount"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PortListResult {
        const $$createField0_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField0_0($$parsedSource["ports"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new PortListResult($$parsedSource as Partial<PortListResult>);
    }
}

/**
 * ServiceEntry 描述一条 Windows 服务，v2 支持停止/启动。
 */
export class ServiceEntry {
    "name": string;
    "displayName": string;

    /**
     * 运行中 / 已停止 / 已暂停 / 未知
     */
    "state": string;

    /**
     * 自动 / 手动 / 禁用 / 未知
     */
    "startType": string;

    /** Creates a new ServiceEntry instance. */
    constructor($$source: Partial<ServiceEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("startType" in $$source)) {
            this["startType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceEntry($$parsedSource as Partial<ServiceEntry>);
    }
}

/**
 * ServiceOpResult 是服务停止/启动操作的结果。
 */
export class ServiceOpResult {
    "name": string;

    /**
     * "stop" / "start"
     */
    "action": string;
    "message": string;

    /** Creates a new ServiceOpResult instance. */
    constructor($$source: Partial<ServiceOpResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceOpResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceOpResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceOpResult($$parsedSource as Partial<ServiceOpResult>);
    }
}

/**
 * Settings 是应用的用户可配置项。
 */
export class Settings {
    "theme": string;
    "refreshIntervalMs": number;
    "language": string;

    /**
     * currentUser / system
     */
    "processScope": string;

    /**
     * 性能悬浮窗开关，默认关闭
     */
    "overlayEnabled": boolean;

    /**
     * topLeft / topRight，默认 topRight
     */
    "overlayPosition": string;

    /**
     * white/red/green/blue/yellow，默认 white
     */
    "overlayColor": string;

    /**
     * 10-18，默认 12
     */
    "overlayFontSize": number;

    /**
     * 用量悬浮窗开关，默认关闭
     */
    "usageOverlayEnabled": boolean;

    /**
     * topLeft / topRight，默认 topRight
     */
    "usageOverlayPosition": string;

    /**
     * used / remaining，默认 used
     */
    "usageOverlayMode": string;

    /**
     * 用量查询自动刷新间隔（分钟），默认 5
     */
    "codingPlanRefreshMinutes": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("refreshIntervalMs" in $$source)) {
            this["refreshIntervalMs"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("processScope" in $$source)) {
            this["processScope"] = "";
        }
        if (!("overlayEnabled" in $$source)) {
            this["overlayEnabled"] = false;
        }
        if (!("overlayPosition" in $$source)) {
            this["overlayPosition"] = "";
        }
        if (!("overlayColor" in $$source)) {
            this["overlayColor"] = "";
        }
        if (!("overlayFontSize" in $$source)) {
            this["overlayFontSize"] = 0;
        }
        if (!("usageOverlayEnabled" in $$source)) {
            this["usageOverlayEnabled"] = false;
        }
        if (!("usageOverlayPosition" in $$source)) {
            this["usageOverlayPosition"] = "";
        }
        if (!("usageOverlayMode" in $$source)) {
            this["usageOverlayMode"] = "";
        }
        if (!("codingPlanRefreshMinutes" in $$source)) {
            this["codingPlanRefreshMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * StartupEntry 描述一条开机启动项，v2 支持删除/禁用/启用。
 */
export class StartupEntry {
    "name": string;
    "command": string;

    /**
     * HKCU / HKLM / StartupFolder
     */
    "location": string;

    /**
     * 来自 StartupApproved
     */
    "disabled": boolean;

    /**
     * 应用图标 data:image/png;base64,... ；失败为空
     */
    "iconDataUrl": string;

    /** Creates a new StartupEntry instance. */
    constructor($$source: Partial<StartupEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }
        if (!("iconDataUrl" in $$source)) {
            this["iconDataUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupEntry($$parsedSource as Partial<StartupEntry>);
    }
}

/**
 * StartupOpResult 是启动项删除/禁用/启用操作的结果。
 */
export class StartupOpResult {
    "name": string;

    /**
     * "delete" / "disable" / "enable"
     */
    "action": string;
    "message": string;

    /** Creates a new StartupOpResult instance. */
    constructor($$source: Partial<StartupOpResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupOpResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupOpResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupOpResult($$parsedSource as Partial<StartupOpResult>);
    }
}

/**
 * UpdateInfo 是检查更新的返回结果。
 */
export class UpdateInfo {
    /**
     * 本地版本
     */
    "currentVersion": string;

    /**
     * 最新 Release 版本（已去掉前缀 v）
     */
    "latestVersion": string;

    /**
     * 是否有新版本
     */
    "hasUpdate": boolean;

    /**
     * Release 页面地址
     */
    "releaseUrl": string;

    /**
     * 第一个资产下载地址（可能为空）
     */
    "downloadUrl": string;

    /**
     * Windows 一键安装包地址（-installer.exe，可能为空）
     */
    "installerUrl": string;

    /**
     * Release 说明
     */
    "notes": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            this["downloadUrl"] = "";
        }
        if (!("installerUrl" in $$source)) {
            this["installerUrl"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = CodingPlanQuota.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CodingPlanBalance.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = PortEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
