// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KillProcessResult {
    "pid": number;
    "message": string;

    /** Creates a new KillProcessResult instance. */
    constructor($$source: Partial<KillProcessResult> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillProcessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KillProcessResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillProcessResult($$parsedSource as Partial<KillProcessResult>);
    }
}

export class PortEntry {
    "protocol": string;
    "localAddr": string;
    "localPort": number;
    "remoteAddr": string;
    "remotePort": number;
    "state": string;
    "pid": number;
    "process": string;
    "path": string;

    /** Creates a new PortEntry instance. */
    constructor($$source: Partial<PortEntry> = {}) {
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("process" in $$source)) {
            this["process"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PortEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortEntry($$parsedSource as Partial<PortEntry>);
    }
}

export class PortListResult {
    "ports": PortEntry[];
    "tcpCount": number;
    "udpCount": number;
    "listeningCount": number;
    "processCount": number;
    "warnings": string[];

    /** Creates a new PortListResult instance. */
    constructor($$source: Partial<PortListResult> = {}) {
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("tcpCount" in $$source)) {
            this["tcpCount"] = 0;
        }
        if (!("udpCount" in $$source)) {
            this["udpCount"] = 0;
        }
        if (!("listeningCount" in $$source)) {
            this["listeningCount"] = 0;
        }
        if (!("processCount" in $$source)) {
            this["processCount"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PortListResult {
        const $$createField0_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField0_0($$parsedSource["ports"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new PortListResult($$parsedSource as Partial<PortListResult>);
    }
}

// Private type creation functions
const $$createType0 = PortEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
