// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KillProcessResult {
    "pid": number;
    "message": string;

    /** Creates a new KillProcessResult instance. */
    constructor($$source: Partial<KillProcessResult> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillProcessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KillProcessResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillProcessResult($$parsedSource as Partial<KillProcessResult>);
    }
}

export class PortEntry {
    "protocol": string;
    "localAddr": string;
    "localPort": number;
    "remoteAddr": string;
    "remotePort": number;
    "state": string;
    "pid": number;
    "process": string;
    "path": string;

    /** Creates a new PortEntry instance. */
    constructor($$source: Partial<PortEntry> = {}) {
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("process" in $$source)) {
            this["process"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PortEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortEntry($$parsedSource as Partial<PortEntry>);
    }
}

export class PortListResult {
    "ports": PortEntry[];
    "tcpCount": number;
    "udpCount": number;
    "listeningCount": number;
    "processCount": number;
    "warnings": string[];

    /** Creates a new PortListResult instance. */
    constructor($$source: Partial<PortListResult> = {}) {
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("tcpCount" in $$source)) {
            this["tcpCount"] = 0;
        }
        if (!("udpCount" in $$source)) {
            this["udpCount"] = 0;
        }
        if (!("listeningCount" in $$source)) {
            this["listeningCount"] = 0;
        }
        if (!("processCount" in $$source)) {
            this["processCount"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PortListResult {
        const $$createField0_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField0_0($$parsedSource["ports"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new PortListResult($$parsedSource as Partial<PortListResult>);
    }
}

/**
 * ServiceEntry 描述一条 Windows 服务，v1 只读。
 */
export class ServiceEntry {
    "name": string;
    "displayName": string;

    /**
     * 运行中 / 已停止 / 已暂停 / 未知
     */
    "state": string;

    /**
     * 自动 / 手动 / 禁用 / 未知
     */
    "startType": string;

    /** Creates a new ServiceEntry instance. */
    constructor($$source: Partial<ServiceEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("startType" in $$source)) {
            this["startType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceEntry($$parsedSource as Partial<ServiceEntry>);
    }
}

/**
 * StartupEntry 描述一条开机启动项，v1 只读。
 */
export class StartupEntry {
    "name": string;
    "command": string;

    /**
     * HKCU / HKLM / StartupFolder
     */
    "location": string;

    /** Creates a new StartupEntry instance. */
    constructor($$source: Partial<StartupEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupEntry($$parsedSource as Partial<StartupEntry>);
    }
}

/**
 * UpdateInfo 是检查更新的返回结果。
 */
export class UpdateInfo {
    /**
     * 本地版本
     */
    "currentVersion": string;

    /**
     * 最新 Release 版本（已去掉前缀 v）
     */
    "latestVersion": string;

    /**
     * 是否有新版本
     */
    "hasUpdate": boolean;

    /**
     * Release 页面地址
     */
    "releaseUrl": string;

    /**
     * 第一个资产下载地址（可能为空）
     */
    "downloadUrl": string;

    /**
     * Release 说明
     */
    "notes": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            this["downloadUrl"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = PortEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
