// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitorService 负责每秒采样进程/性能/端口统计，合并为单个事件推送给前端，
 * 是高频刷新场景下"批量推送取代频繁 RPC"的核心。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SetInterval 动态调整采样推送间隔（毫秒），范围 200-10000；超范围自动钳位。
 */
export function SetInterval(ms: number): $CancellablePromise<void> {
    return $Call.ByID(3464076596, ms);
}
