// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OverlayService 负责管理「性能悬浮窗」这一独立、置顶、无边框的小窗口生命周期。
 * 它与主窗口完全解耦：主窗口最小化到托盘不影响悬浮窗；悬浮窗显隐只由设置项驱动。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Apply 是前端可调用的 RPC：按 (enabled, position) 创建 / 移动 / 关闭悬浮窗。
 *   - enabled=false：关闭并丢弃窗口引用。
 *   - enabled=true 且窗口不存在：按 position 计算坐标后创建置顶无边框窗口。
 *   - enabled=true 且窗口已存在：仅按 position 重新定位。
 */
export function Apply(enabled: boolean, position: string): $CancellablePromise<void> {
    return $Call.ByID(1908243403, enabled, position);
}

/**
 * RestoreIfEnabled 在主窗口前端加载完成后恢复悬浮窗。
 * 仅在启动时记录了恢复意图时生效，调用一次后清空标记，防止重复触发。
 */
export function RestoreIfEnabled(): $CancellablePromise<void> {
    return $Call.ByID(3917557527);
}
