// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function KillProcess(pid: number): $CancellablePromise<$models.KillProcessResult> {
    return $Call.ByID(1369868295, pid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListPorts(): $CancellablePromise<$models.PortListResult> {
    return $Call.ByID(2476916090).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.KillProcessResult.createFrom;
const $$createType1 = $models.PortListResult.createFrom;
