// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServicesService 提供只读的 Windows 服务枚举（v1 不含启停写操作）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListServices 以只读方式枚举所有 Windows 服务。
 * 仅需 SC_MANAGER_ENUMERATE_SERVICE 权限，标准用户即可调用；
 * 单次 EnumServicesStatusEx 同时拿到 名称/显示名/状态/类型/进程ID，无需逐个 OpenService。
 */
export function ListServices(): $CancellablePromise<$models.ServiceEntry[]> {
    return $Call.ByID(3319457421).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ServiceEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
