// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 提供持久化配置读写与开机自启管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings 读取配置；文件不存在时返回默认值并写入一份。
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsElevated 返回当前进程是否以管理员权限运行（进程范围=system 的运行时前提）。
 */
export function IsElevated(): $CancellablePromise<boolean> {
    return $Call.ByID(457530734);
}

/**
 * RelaunchElevated 以管理员权限重启应用本体：runas 启动新实例后延时退出旧实例。
 * 用于切换到"整个系统"进程范围；新实例以管理员身份启动后即可全量枚举进程。
 */
export function RelaunchElevated(): $CancellablePromise<void> {
    return $Call.ByID(3205862940);
}

/**
 * SaveSettings 持久化设置到 JSON 文件。
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2662658340, settings);
}

/**
 * SetAutostart 设置/取消 PortCheck 开机自启（HKCU 注册表 Run 键）。
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(848055361, enabled);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
