// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupService 提供开机启动项枚举与删除/禁用/启用（v2）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteStartup 删除启动项；权限不足时自动 UAC 提权重试。
 */
export function DeleteStartup(name: string, location: string): $CancellablePromise<$models.StartupOpResult> {
    return $Call.ByID(241610216, name, location).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DisableStartup 禁用启动项（可恢复）；权限不足时自动 UAC 提权重试。
 */
export function DisableStartup(name: string, location: string): $CancellablePromise<$models.StartupOpResult> {
    return $Call.ByID(3722831081, name, location).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * EnableStartup 启用已禁用的启动项；权限不足时自动 UAC 提权重试。
 */
export function EnableStartup(name: string, location: string): $CancellablePromise<$models.StartupOpResult> {
    return $Call.ByID(3662138668, name, location).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListStartup 枚举开机启动项：
 * 覆盖 HKCU / HKLM 的 Run 键，以及当前用户的 Startup 文件夹；并回填禁用状态。
 */
export function ListStartup(): $CancellablePromise<$models.StartupEntry[]> {
    return $Call.ByID(3162782277).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.StartupOpResult.createFrom;
const $$createType1 = $models.StartupEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
