// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupService 提供只读的开机启动项枚举（v1 不含启用/禁用写操作）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListStartup 以只读方式枚举开机启动项：
 * 覆盖 HKCU / HKLM 的 Run 键，以及当前用户的 Startup 文件夹（v1 不做启用/禁用）。
 */
export function ListStartup(): $CancellablePromise<$models.StartupEntry[]> {
    return $Call.ByID(3162782277).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.StartupEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
