// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 提供检查更新能力：请求 GitHub 最新 Release，与本地版本对比。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate 查询 GitHub 最新 Release 并与本地版本对比。
 * 使用未认证请求，受 GitHub 60 次/小时/IP 限制；手动触发场景足够。
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(887052505).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CurrentVersion 返回当前应用版本号，供前端展示或诊断使用。
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(212359031);
}

/**
 * OpenURL 用系统默认浏览器打开指定网址（用于跳转 Release 下载页）。
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1881926105, url);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
